// tailwind.config.js
/** @type {import('tailwindcss').Config} */
export default {
  prefix: "astralis-",
  content: ["./src/**/*.{ts,tsx}", "./.storybook/**/*.{ts,tsx}"],
  darkMode: ["class", ".astralis-dark"],
  theme: {
    extend: {
      colors: {
        // All colors now point to CSS variables
        primary: {
          50: "var(--astralis-primary-50)",
          100: "var(--astralis-primary-100)",
          200: "var(--astralis-primary-200)",
          300: "var(--astralis-primary-300)",
          400: "var(--astralis-primary-400)",
          500: "var(--astralis-primary-500)",
          600: "var(--astralis-primary-600)",
          700: "var(--astralis-primary-700)",
          800: "var(--astralis-primary-800)",
          900: "var(--astralis-primary-900)",
        },
        secondary: {
          50: "var(--astralis-secondary-50)",
          100: "var(--astralis-secondary-100)",
          200: "var(--astralis-secondary-200)",
          300: "var(--astralis-secondary-300)",
          400: "var(--astralis-secondary-400)",
          500: "var(--astralis-secondary-500)",
          600: "var(--astralis-secondary-600)",
          700: "var(--astralis-secondary-700)",
          800: "var(--astralis-secondary-800)",
          900: "var(--astralis-secondary-900)",
        },
        success: {
          50: "var(--astralis-success-50)",
          100: "var(--astralis-success-100)",
          200: "var(--astralis-success-200)",
          300: "var(--astralis-success-300)",
          400: "var(--astralis-success-400)",
          500: "var(--astralis-success-500)",
          600: "var(--astralis-success-600)",
          700: "var(--astralis-success-700)",
          800: "var(--astralis-success-800)",
          900: "var(--astralis-success-900)",
        },
        warning: {
          50: "var(--astralis-warning-50)",
          100: "var(--astralis-warning-100)",
          200: "var(--astralis-warning-200)",
          300: "var(--astralis-warning-300)",
          400: "var(--astralis-warning-400)",
          500: "var(--astralis-warning-500)",
          600: "var(--astralis-warning-600)",
          700: "var(--astralis-warning-700)",
          800: "var(--astralis-warning-800)",
          900: "var(--astralis-warning-900)",
        },
        error: {
          50: "var(--astralis-error-50)",
          100: "var(--astralis-error-100)",
          200: "var(--astralis-error-200)",
          300: "var(--astralis-error-300)",
          400: "var(--astralis-error-400)",
          500: "var(--astralis-error-500)",
          600: "var(--astralis-error-600)",
          700: "var(--astralis-error-700)",
          800: "var(--astralis-error-800)",
          900: "var(--astralis-error-900)",
        },
        // Semantic surface tokens - these are what your components should use
        surface: {
          base: "var(--astralis-surface-base)",
          raised: "var(--astralis-surface-raised)",
          overlay: "var(--astralis-surface-overlay)",
          popover: "var(--astralis-surface-popover)",
          sunken: "var(--astralis-surface-sunken)",
        },
        content: {
          primary: "var(--astralis-content-primary)",
          secondary: "var(--astralis-content-secondary)",
          tertiary: "var(--astralis-content-tertiary)",
          inverse: "var(--astralis-content-inverse)",
          disabled: "var(--astralis-content-disabled)",
        },
        border: {
          strong: "var(--astralis-border-strong)",
          subtle: "var(--astralis-border-subtle)",
        },
      },
    },
  },
  plugins: [],
};