/**
 * Seed <-> CSS/JSON, the round trip.
 *
 * `themeCss` is the one serializer: the CLI, the docs theme builder, and any
 * consumer exporting a theme all go through it, so a generated stylesheet can
 * never drift from what <AstralisProvider tokens={seed}> would produce at
 * runtime — same math (theme-math), same spec (token-spec), same escaping.
 *
 * `parseThemeSeed` reads a seed back out of either the JSON form or a
 * stylesheet this module wrote, so a saved theme can be reopened for editing.
 *
 * Dependency- and React-free like its neighbours: runs in Node for the CLI and
 * in the browser for the builder.
 */

import { generateThemeTokens } from "./theme-math";
import { SPACING_SCALE, RADIUS_SCALE, FONT_SIZE_SCALE, DURATION_SCALE } from "./token-spec";
import type { ThemeSeed } from "./token-spec";

/* ==========================================================================
   SERIALIZE
   ========================================================================== */

const HEX = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i;

/**
 * Fields that carry a colour, and the palette each seeds. Status colours seed
 * their own role palette, never the hue it aliases (see ROLE_PALETTES).
 */
const COLOR_PALETTES = {
  brandColor: "brand",
  grayColor: "gray",
  errorColor: "error",
  warningColor: "warning",
  successColor: "success",
  infoColor: "info",
} as const;

const COLOR_FIELDS = Object.keys(COLOR_PALETTES) as (keyof typeof COLOR_PALETTES)[];
/** Fields that carry a font stack. */
const FONT_FIELDS = ["fontHeading", "fontBody", "fontMono"] as const;
/** Fields that carry a scale multiplier. */
const SCALE_FIELDS = ["radiusScale", "spacingScale", "fontSizeScale", "motionScale"] as const;

export type SeedIssue = { field: string; message: string };

/**
 * Rejects values that would produce nonsense CSS. Scales allow 0 (squared-off
 * corners, motion disabled) but not negatives, which would emit negative rem.
 */
export function validateSeed(seed: ThemeSeed): SeedIssue[] {
  const issues: SeedIssue[] = [];
  for (const field of COLOR_FIELDS) {
    const value = seed[field];
    if (value !== undefined && !HEX.test(value)) {
      issues.push({ field, message: `"${value}" is not a hex colour — expected #rgb or #rrggbb.` });
    }
  }
  for (const field of SCALE_FIELDS) {
    const value = seed[field];
    if (value === undefined) continue;
    if (!Number.isFinite(value)) issues.push({ field, message: `must be a finite number.` });
    else if (value < 0) issues.push({ field, message: `must not be negative (got ${value}).` });
  }
  return issues;
}

/** True when the seed would produce no overrides at all. */
export function isEmptySeed(seed: ThemeSeed | undefined): boolean {
  if (!seed) return true;
  return Object.keys(generateThemeTokens(seed, "light", { forCss: true })).length === 0;
}

const block = (selector: string, vars: Record<string, string>): string[] =>
  Object.keys(vars).length === 0
    ? []
    : [
        "",
        `${selector} {`,
        ...Object.entries(vars).map(([name, value]) => `  ${name}: ${value};`),
        "}",
      ];

export interface ThemeCssOptions {
  /** Overrides the default file banner. */
  banner?: string;
}

/**
 * A seed as a stylesheet: a `:root` block plus a `.astralis-dark` block for
 * whatever differs in dark mode.
 *
 * Import order matters — these are plain `:root` declarations competing with
 * the library's own, and both are unlayered, so ordinary source order decides.
 * Loaded before astralis-ui/styles.css they are silently overridden.
 *
 * Returns "" for a seed with nothing to say, so callers can skip writing a
 * file that would do nothing.
 */
export function themeCss(seed: ThemeSeed | undefined, options: ThemeCssOptions = {}): string {
  if (!seed) return "";

  const light = generateThemeTokens(seed, "light", { forCss: true });
  const dark = generateThemeTokens(seed, "dark", { forCss: true });
  if (Object.keys(light).length === 0 && Object.keys(dark).length === 0) return "";

  // Only mode-dependent tokens need repeating under .astralis-dark.
  const darkOnly: Record<string, string> = {};
  for (const [name, value] of Object.entries(dark)) {
    if (light[name] !== value) darkOnly[name] = value;
  }

  const banner =
    options.banner ??
    [
      "/* Generated by astralis-ui — a theme seed as plain CSS.",
      " * Import AFTER \"astralis-ui/styles.css\" so these overrides win.",
      " * Runtime equivalent: <AstralisProvider tokens={…}> — same math.",
      " */",
    ].join("\n");

  return [
    banner,
    `/* astralis-seed: ${JSON.stringify(seed)} */`,
    ...block(":root", light),
    ...block(".astralis-dark", darkOnly),
    "",
  ].join("\n");
}

/* ==========================================================================
   PARSE
   ========================================================================== */

const SCALE_TABLES: Record<string, { table: Record<string, number>; group: string }> = {
  spacingScale: { table: SPACING_SCALE, group: "spacing" },
  radiusScale: { table: RADIUS_SCALE, group: "border-radius" },
  fontSizeScale: { table: FONT_SIZE_SCALE, group: "font-size" },
  motionScale: { table: DURATION_SCALE, group: "duration" },
};

/** Accepts a seed-shaped object, ignoring unknown keys and wrong types. */
function coerceSeed(input: unknown): ThemeSeed {
  const seed: ThemeSeed = {};
  if (typeof input !== "object" || input === null) return seed;
  const raw = input as Record<string, unknown>;
  for (const field of [...COLOR_FIELDS, ...FONT_FIELDS]) {
    const value = raw[field];
    if (typeof value === "string" && value.trim() !== "") seed[field] = value;
  }
  for (const field of SCALE_FIELDS) {
    const value = raw[field];
    if (typeof value === "number" && Number.isFinite(value)) seed[field] = value;
  }
  return seed;
}

/**
 * Recovers the seed from a stylesheet written by `themeCss`.
 *
 * Prefers the `astralis-seed:` comment, which is exact. Without it — a
 * hand-edited or third-party file — the seed is INFERRED from the emitted
 * values: the brand ramp's 500 step, and each scale's ratio against its base
 * table. Inference is necessarily lossy (a ramp that was hand-tweaked will not
 * reproduce), so the comment is what makes the round trip lossless.
 */
export function parseThemeCss(css: string): ThemeSeed {
  const tagged = /\/\*\s*astralis-seed:\s*(\{[\s\S]*?\})\s*\*\//.exec(css);
  if (tagged) {
    try {
      return coerceSeed(JSON.parse(tagged[1]));
    } catch {
      // Fall through to inference — a corrupt comment should not lose the file.
    }
  }

  const seed: ThemeSeed = {};
  const declared = new Map<string, string>();
  for (const m of css.matchAll(/(--astralis-[a-z0-9\\./-]+)\s*:\s*([^;]+);/gi)) {
    declared.set(m[1].replace(/\\/g, ""), m[2].trim());
  }

  // Every seeded palette puts its input at step 500, so that step IS the seed.
  for (const [field, palette] of Object.entries(COLOR_PALETTES)) {
    const value = declared.get(`--astralis-color-${palette}-500`);
    if (value && HEX.test(value)) seed[field as keyof typeof COLOR_PALETTES] = value;
  }

  const fonts = {
    fontHeading: "--astralis-font-heading",
    fontBody: "--astralis-font-body",
    fontMono: "--astralis-font-mono",
  } as const;
  for (const [field, name] of Object.entries(fonts)) {
    const value = declared.get(name);
    if (value) seed[field as keyof typeof fonts] = value;
  }

  for (const [field, { table, group }] of Object.entries(SCALE_TABLES)) {
    /*
     * The factor is uniform across the ramp, so one step suffices — but which
     * step matters. Emitted values are rounded (4dp for rem, whole ms), and
     * that rounding is a larger *proportion* of a small base: recovering 1.5
     * from radius 2xs (0.0625 -> 0.0938) yields 1.5008, while the largest step
     * (2rem -> 3rem) is exact. So read the biggest step available.
     */
    const steps = Object.entries(table)
      .filter(([, base]) => base > 0)
      .sort((a, b) => b[1] - a[1]);

    for (const [step, base] of steps) {
      const value = declared.get(`--astralis-${group}-${step}`);
      if (!value) continue;
      const n = parseFloat(value);
      if (!Number.isFinite(n)) continue;
      seed[field as (typeof SCALE_FIELDS)[number]] = parseFloat((n / base).toFixed(4));
      break;
    }
  }
  return seed;
}

/**
 * Reads a seed from JSON or from generated CSS, whichever it is handed. The
 * builder accepts pasted input without asking the user which format it is.
 */
export function parseThemeSeed(input: string): ThemeSeed {
  const text = input.trim();
  if (text.startsWith("{")) {
    try {
      return coerceSeed(JSON.parse(text));
    } catch {
      return {};
    }
  }
  return parseThemeCss(text);
}
