export const flexDirectionTypes = {
  row: "astralis:flex-row",
  column: "astralis:flex-col",
  "row-reverse": "astralis:flex-row-reverse",
  "column-reverse": "astralis:flex-col-reverse",
};

export const flexJustifyTypes = {
  start: "astralis:justify-start",
  center: "astralis:justify-center",
  end: "astralis:justify-end",
  between: "astralis:justify-between",
  around: "astralis:justify-around",
  evenly: "astralis:justify-evenly",
};

export const flexAlignTypes = {
  start: "astralis:items-start",
  center: "astralis:items-center",
  end: "astralis:items-end",
  baseline: "astralis:items-baseline",
  stretch: "astralis:items-stretch",
};

export const flexWrapTypes = {
  wrap: "astralis:flex-wrap",
  nowrap: "astralis:flex-nowrap",
  "wrap-reverse": "astralis:flex-wrap-reverse",
};

export const gapTypes = {
  "0.5": "astralis:gap-0.5",
  "1": "astralis:gap-1",
  "1.5": "astralis:gap-1.5",
  "2": "astralis:gap-2",
  "2.5": "astralis:gap-2.5",
  "3": "astralis:gap-3",
  "3.5": "astralis:gap-3.5",
  "4": "astralis:gap-4",
  "4.5": "astralis:gap-4.5",
  "5": "astralis:gap-5",
  "6": "astralis:gap-6",
  "7": "astralis:gap-7",
  "8": "astralis:gap-8",
  "9": "astralis:gap-9",
  "10": "astralis:gap-10",
  "11": "astralis:gap-11",
  "12": "astralis:gap-12",
  "14": "astralis:gap-14",
  "16": "astralis:gap-16",
  "20": "astralis:gap-20",
  "24": "astralis:gap-24",
  "28": "astralis:gap-28",
  "32": "astralis:gap-32",
  "36": "astralis:gap-36",
  "40": "astralis:gap-40",
  "44": "astralis:gap-44",
  "48": "astralis:gap-48",
  "52": "astralis:gap-52",
  "56": "astralis:gap-56",
  "60": "astralis:gap-60",
  "64": "astralis:gap-64",
  "72": "astralis:gap-72",
  "80": "astralis:gap-80",
  "96": "astralis:gap-96",
};

export const rowGapTypes = {
  "0.5": "astralis:gap-y-0.5",
  "1": "astralis:gap-y-1",
  "1.5": "astralis:gap-y-1.5",
  "2": "astralis:gap-y-2",
  "2.5": "astralis:gap-y-2.5",
  "3": "astralis:gap-y-3",
  "3.5": "astralis:gap-y-3.5",
  "4": "astralis:gap-y-4",
  "4.5": "astralis:gap-y-4.5",
  "5": "astralis:gap-y-5",
  "6": "astralis:gap-y-6",
  "7": "astralis:gap-y-7",
  "8": "astralis:gap-y-8",
  "9": "astralis:gap-y-9",
  "10": "astralis:gap-y-10",
  "11": "astralis:gap-y-11",
  "12": "astralis:gap-y-12",
  "14": "astralis:gap-y-14",
  "16": "astralis:gap-y-16",
  "20": "astralis:gap-y-20",
  "24": "astralis:gap-y-24",
  "28": "astralis:gap-y-28",
  "32": "astralis:gap-y-32",
  "36": "astralis:gap-y-36",
  "40": "astralis:gap-y-40",
  "44": "astralis:gap-y-44",
  "48": "astralis:gap-y-48",
  "52": "astralis:gap-y-52",
  "56": "astralis:gap-y-56",
  "60": "astralis:gap-y-60",
  "64": "astralis:gap-y-64",
  "72": "astralis:gap-y-72",
  "80": "astralis:gap-y-80",
  "96": "astralis:gap-y-96",
} as const;

export const columnGapTypes = {
  "0.5": "astralis:gap-x-0.5",
  "1": "astralis:gap-x-1",
  "1.5": "astralis:gap-x-1.5",
  "2": "astralis:gap-x-2",
  "2.5": "astralis:gap-x-2.5",
  "3": "astralis:gap-x-3",
  "3.5": "astralis:gap-x-3.5",
  "4": "astralis:gap-x-4",
  "4.5": "astralis:gap-x-4.5",
  "5": "astralis:gap-x-5",
  "6": "astralis:gap-x-6",
  "7": "astralis:gap-x-7",
  "8": "astralis:gap-x-8",
  "9": "astralis:gap-x-9",
  "10": "astralis:gap-x-10",
  "11": "astralis:gap-x-11",
  "12": "astralis:gap-x-12",
  "14": "astralis:gap-x-14",
  "16": "astralis:gap-x-16",
  "20": "astralis:gap-x-20",
  "24": "astralis:gap-x-24",
  "28": "astralis:gap-x-28",
  "32": "astralis:gap-x-32",
  "36": "astralis:gap-x-36",
  "40": "astralis:gap-x-40",
  "44": "astralis:gap-x-44",
  "48": "astralis:gap-x-48",
  "52": "astralis:gap-x-52",
  "56": "astralis:gap-x-56",
  "60": "astralis:gap-x-60",
  "64": "astralis:gap-x-64",
  "72": "astralis:gap-x-72",
  "80": "astralis:gap-x-80",
  "96": "astralis:gap-x-96",
} as const;