import { parseArgs } from "node:util";
import { existsSync, writeFileSync } from "node:fs";
import { generateBrandTokens } from "astralis-ui/color-math";
import { ok, fail, cyan, dim } from "../lib/ui.mjs";

const HEX_PATTERN = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i;

const serialize = (vars) =>
  Object.entries(vars)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");

/**
 * The static equivalent of `<AstralisProvider tokens={{ brandColor }}>` —
 * same OKLCH math (imported from the library, never duplicated), rendered as
 * a stylesheet for people who prefer build-time theming over the runtime
 * provider. Must be imported AFTER astralis-ui/styles.css so the cascade
 * lets these :root declarations win.
 */
export function themeCss(hex) {
  const light = generateBrandTokens(hex, "light");
  const dark = generateBrandTokens(hex, "dark");
  return [
    `/* Generated by astralis-cli — brand ramp for ${hex}.`,
    ` * Import AFTER "astralis-ui/styles.css" so these overrides win. */`,
    "",
    ":root {",
    serialize(light),
    "}",
    "",
    ".astralis-dark {",
    serialize(dark),
    "}",
    "",
  ].join("\n");
}

export async function run(argv) {
  const { values, positionals } = parseArgs({
    args: argv,
    options: {
      out: { type: "string", default: "astralis-theme.css" },
      force: { type: "boolean", default: false },
    },
    allowPositionals: true,
  });

  const hex = positionals[0];
  if (!hex) fail('Usage: astralis theme "#8b5cf6" [--out astralis-theme.css] [--force]');
  if (!HEX_PATTERN.test(hex)) fail(`"${hex}" is not a hex color — expected #rgb or #rrggbb.`);
  if (existsSync(values.out) && !values.force) {
    fail(`${values.out} already exists — pass --force to overwrite.`);
  }

  writeFileSync(values.out, themeCss(hex.toLowerCase()));
  ok(`wrote ${cyan(values.out)}`);
  console.log(`\nImport it after the library stylesheet:\n  ${cyan('import "astralis-ui/styles.css";')}\n  ${cyan(`import "./${values.out}";`)}\n${dim("(Runtime alternative: <AstralisProvider tokens={{ brandColor }}> — same math.)")}`);
}
